# Generated by Django 5.2.6 on 2025-10-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('first_contact', models.DateTimeField()),
                ('last_contact', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=128, unique=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('company_source', models.CharField(blank=True, max_length=50)),
                ('sender', models.CharField(max_length=256)),
                ('sender_domain', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=128)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionStats',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_fetched', models.IntegerField(default=0)),
                ('total_inserted', models.IntegerField(default=0)),
                ('total_ignored', models.IntegerField(default=0)),
                ('total_skipped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnresolvedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=128, unique=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=256)),
                ('sender_domain', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('company_source', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('sent_date', models.DateField()),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('ml_label', models.CharField(blank=True, max_length=50, null=True)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.company')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_source', models.CharField(blank=True, max_length=50, null=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('msg_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('ml_label', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.company')),
            ],
        ),
    ]
