# Generated by Django 4.2.25 on 2025-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ignoredmessage",
            name="company_source",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
