# Generated by Django 5.2.6 on 2025-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
