# Generated by Django 5.2.6 on 2025-10-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
