# Generated by Django 5.2.6 on 2025-10-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="homepage",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("application", "Application"),
                    ("interview", "Interview"),
                    ("follow-up", "Follow-up"),
                    ("rejected", "Rejected"),
                    ("ghosted", "Ghosted"),
                ],
                default="application",
                max_length=32,
                null=True,
            ),
        ),
    ]
