# Generated by Django 4.2.25 on 2025-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_ignoredmessage_company_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="company_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
