# Generated by Django 5.2.6 on 2025-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_company_contact_email_company_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ats",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
