# Generated by Django 5.2.6 on 2025-09-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_application_company_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="thread_id",
            field=models.CharField(
                default="nonInitialized Thread", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
