# Generated by Django 5.2.6 on 2025-10-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
