# Generated by Django 5.2.6 on 2025-10-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_company_ats"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#2563eb", max_length=16)),
            ],
        ),
    ]
