# Generated by Django 4.2.25 on 2025-10-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_message_company_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=128, unique=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=256)),
                ('sender_domain', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
