# Generated by Django 5.2.6 on 2025-09-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_application_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ml_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ml_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
