# Generated by Django 5.2.6 on 2025-09-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_application_ml_confidence_application_ml_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.company",
            ),
        ),
    ]
