# Generated by Django 5.2.7 on 2025-10-19 04:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_messagelabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trained_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("n_samples", models.IntegerField()),
                ("n_classes", models.IntegerField()),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("macro_precision", models.FloatField(blank=True, null=True)),
                ("macro_recall", models.FloatField(blank=True, null=True)),
                ("macro_f1", models.FloatField(blank=True, null=True)),
                ("weighted_precision", models.FloatField(blank=True, null=True)),
                ("weighted_recall", models.FloatField(blank=True, null=True)),
                ("weighted_f1", models.FloatField(blank=True, null=True)),
                ("label_distribution", models.TextField()),
                ("classification_report", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelTrainingLabelMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1", models.FloatField(blank=True, null=True)),
                ("support", models.IntegerField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_metrics",
                        to="tracker.modeltrainingrun",
                    ),
                ),
            ],
        ),
    ]
