# Generated by Django 5.2.6 on 2025-10-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_company_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
