# Generated by Django 5.2.6 on 2025-10-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_ingestionstats_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
