# Generated by Django 5.2.6 on 2025-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_message_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=128, unique=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=256)),
                ('sender_domain', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=128)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
