# Generated by Django 5.2.7 on 2025-10-19 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_modeltrainingrun_modeltraininglabelmetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailFilterImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("labels_updated", models.IntegerField(default=0)),
                ("excludes_updated", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("unmatched_labels", models.TextField(blank=True)),
                ("diff_json", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
