# Generated by Django 5.2.6 on 2025-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_ignoredmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_fetched', models.IntegerField(default=0)),
                ('total_inserted', models.IntegerField(default=0)),
                ('total_ignored', models.IntegerField(default=0)),
            ],
        ),
    ]
