# Generated by Django 5.2.7 on 2025-11-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadtracking',
            name='interview_completed',
            field=models.BooleanField(default=False),
        ),
    ]
