# Generated by Django 5.2.6 on 2025-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_ingestionstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionstats',
            name='total_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
