# Generated by Django 5.2.6 on 2025-11-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Formalizes ThreadTracking model Meta options and table name.
    
    The AlterModelTable operation is wrapped in SeparateDatabaseAndState because:
    - The table is already named 'tracker_application' from migration 0001
    - Only the migration state needs updating to match the current code
    - No actual database ALTER TABLE operation is needed
    """

    dependencies = [
        ("tracker", "0008_add_interview_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="threadtracking",
            options={
                "verbose_name": "Thread Tracking",
                "verbose_name_plural": "Thread Tracking",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("application", "Application"),
                    ("interview", "Interview"),
                    ("follow-up", "Follow-up"),
                    ("rejected", "Rejected"),
                    ("ghosted", "Ghosted"),
                    ("headhunter", "HeadHunter"),
                ],
                default="application",
                max_length=32,
                null=True,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="threadtracking",
                    table="tracker_application",
                ),
            ],
            database_operations=[
                # No-op: table is already named 'tracker_application' from 0001
                migrations.RunSQL("SELECT 1", reverse_sql="SELECT 1"),
            ],
        ),
    ]
