# Generated by Django 5.2.6 on 2025-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_ingestionstats_total_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ml_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
