# Generated by Django 5.2.6 on 2025-10-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_message_ml_label_message_msg_id_message_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
