# Generated by ChatGPT - add AuditEvent model
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_threadtracking_options_alter_company_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(max_length=80)),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('db_id', models.IntegerField(blank=True, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('trace', models.TextField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='tracker_audite_created_at_idx')],
            },
        ),
    ]
