# Generated by Django 4.2.25 on 2025-12-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_audit_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="tracker_aud_created_3a07bf_idx",
            old_name="tracker_audite_created_at_idx",
        ),
        migrations.AddField(
            model_name="message",
            name="body_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
