# Generated by Django 5.2.6 on 2025-10-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_message_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
