# Generated by Django 5.2.6 on 2025-10-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_message_confidence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingestionstats",
            name="id",
        ),
        migrations.AlterField(
            model_name="ingestionstats",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
