# Generated by Django 4.2.25 on 2025-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_tracker_audite_created_at_idx_tracker_aud_created_3a07bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classification_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
