# Generated by Django 4.2.25 on 2026-01-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_add_classification_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Free-form notes about the company", null=True
            ),
        ),
    ]
