# Generated by Django 4.2.25 on 2026-01-07 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_add_company_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ats',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_ats', message='ATS domain can only contain letters, numbers, dots, and hyphens', regex='^[a-zA-Z0-9.\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_contact_name', message="Contact name can only contain letters, spaces, and: . , - '", regex="^[a-zA-Z\\s.,\\-\\']+$")]),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Domain can only contain letters, numbers, dots, and hyphens', regex='^[a-zA-Z0-9.\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='homepage',
            field=models.URLField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_company_name', message='Company name can only contain letters, numbers, spaces, and: . , - & \' " ( )', regex='^[a-zA-Z0-9\\s.,\\-&\\\'"()]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('application', 'Application'), ('interview', 'Interview'), ('follow-up', 'Follow-up'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted'), ('headhunter', 'HeadHunter')], default='application', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='threadtracking',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_job_id', message='Job ID can only contain letters, numbers, hyphens, and underscores', regex='^[a-zA-Z0-9\\-_]*$')]),
        ),
        migrations.AlterField(
            model_name='threadtracking',
            name='job_title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_job_title', message='Job title can only contain letters, numbers, spaces, and: . , - / ( ) &', regex='^[a-zA-Z0-9\\s.,\\-/()&]+$')]),
        ),
        migrations.AlterField(
            model_name='threadtracking',
            name='thread_id',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_thread_id', message='Thread ID can only contain letters and numbers', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
