# Generated by Django 4.2.25 on 2026-01-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_alter_company_ats_alter_company_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="last_job_search_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Last date when user manually searched this company's job postings",
                null=True,
            ),
        ),
    ]
