# Generated by Django 4.2.25 on 2026-01-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_company_last_job_search_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="focus_area",
            field=models.CharField(
                blank=True,
                help_text="Business focus area (e.g., Software as a Service, Mining, Network Security)",
                max_length=255,
                null=True,
            ),
        ),
    ]
