# Generated by Django 4.2.25 on 2026-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_add_focus_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadtracking",
            name="application_text",
            field=models.TextField(
                blank=True, help_text="Cover letter or application text", null=True
            ),
        ),
        migrations.AddField(
            model_name="threadtracking",
            name="application_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the job application page",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="threadtracking",
            name="prescreen_date",
            field=models.DateField(
                blank=True,
                help_text="Date of prescreen phone call or initial screening",
                null=True,
            ),
        ),
    ]
