# Generated by Django 4.2.25 on 2026-01-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_add_prescreen_and_application_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadtracking",
            name="offer_date",
            field=models.DateField(
                blank=True, help_text="Date job offer was received", null=True
            ),
        ),
    ]
