# Generated by Django 4.2.25 on 2026-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_add_offer_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadtracking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="threadtracking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
