# Generated by Django 4.2.25 on 2026-01-17 01:42

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0019_add_created_updated_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("application", "Application"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                    ("follow-up", "Follow-up"),
                    ("rejected", "Rejected"),
                    ("ghosted", "Ghosted"),
                    ("headhunter", "HeadHunter"),
                ],
                default="application",
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Allowed types: PDF, TXT, XLSX, DOCX. Max size: 5MB.",
                        upload_to=tracker.models.company_document_path,
                        validators=[
                            tracker.models.validate_file_size,
                            tracker.models.validate_file_extension,
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of the document (e.g., 'Offer Letter', 'Contract')",
                        max_length=255,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tracker.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
