# Generated by Django 4.2.25 on 2026-01-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0020_company_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadtracking",
            name="cancelled",
            field=models.BooleanField(
                default=False, help_text="Job posting was cancelled by the company"
            ),
        ),
        migrations.AddField(
            model_name="threadtracking",
            name="withdrew",
            field=models.BooleanField(
                default=False, help_text="User withdrew their application"
            ),
        ),
    ]
