# Generated by Django 4.2.25 on 2026-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0021_add_cancelled_withdrew_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadtracking",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Job location (e.g., Remote, New York, NY, Hybrid - San Francisco)",
                max_length=255,
                null=True,
            ),
        ),
    ]
