# Generated by Django 4.2.25 on 2026-02-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0022_add_location_to_threadtracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefenseContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        help_text="Contract or modification number (e.g., W9124P-22-F-0036)",
                        max_length=100,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL of the war.gov article this contract was scraped from",
                        max_length=512,
                    ),
                ),
                (
                    "article_date",
                    models.DateField(
                        help_text="Publication date of the war.gov contracts article"
                    ),
                ),
                (
                    "company_name_raw",
                    models.CharField(
                        help_text="Company name exactly as it appears in the contract text",
                        max_length=255,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("army", "Army"),
                            ("navy", "Navy"),
                            ("air_force", "Air Force"),
                            ("defense_logistics_agency", "Defense Logistics Agency"),
                            ("special_operations", "U.S. Special Operations Command"),
                            ("missile_defense", "Missile Defense Agency"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Military branch or agency awarding the contract",
                        max_length=40,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dollar value of the contract award",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Full description of the contract work"
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="Complete unprocessed paragraph text from the article",
                    ),
                ),
                (
                    "company_location",
                    models.CharField(
                        blank=True,
                        help_text="City, State of the awardee (e.g., Reston, Virginia)",
                        max_length=255,
                    ),
                ),
                (
                    "work_location",
                    models.TextField(
                        blank=True,
                        help_text="Where the work will be performed (may include percentages)",
                    ),
                ),
                (
                    "completion_date",
                    models.CharField(
                        blank=True,
                        help_text="Expected completion date as stated in the contract text",
                        max_length=100,
                    ),
                ),
                (
                    "contracting_activity",
                    models.CharField(
                        blank=True,
                        help_text="Contracting command or office (e.g., Naval Air Systems Command)",
                        max_length=255,
                    ),
                ),
                (
                    "is_modification",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a modification to an existing contract",
                    ),
                ),
                (
                    "is_small_business",
                    models.BooleanField(
                        default=False,
                        help_text="True if the awardee is marked with * (small business)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a tracked Company record, if matched",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defense_contracts",
                        to="tracker.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-article_date", "branch", "company_name_raw"],
                "indexes": [
                    models.Index(
                        fields=["article_date"], name="tracker_def_article_2a145d_idx"
                    ),
                    models.Index(
                        fields=["company_name_raw"],
                        name="tracker_def_company_24af99_idx",
                    ),
                    models.Index(
                        fields=["branch"], name="tracker_def_branch_861ce5_idx"
                    ),
                ],
                "unique_together": {
                    ("source_url", "company_name_raw", "contract_number")
                },
            },
        ),
    ]
