# Generated by Django 4.2.25 on 2026-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0024_add_scraped_article_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scrapedarticle",
            new_name="tracker_scr_article_7166ec_idx",
            old_name="tracker_scra_article_idx",
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Headquarters or office location (e.g., Reston, VA)",
                max_length=255,
                null=True,
            ),
        ),
    ]
