# Generated by Django 4.2.25 on 2026-02-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_add_company_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.JSONField(default=list, help_text='Currently cached articles (limited list for display)')),
                ('all_articles', models.JSONField(default=list, help_text='Historical record of all articles ever fetched')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='When news was last refreshed', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Last error encountered during fetch (if any)')),
                ('cache_duration_hours', models.PositiveIntegerField(default=24, help_text='How many hours before cache expires and refresh needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='tracker.company')),
            ],
            options={
                'verbose_name_plural': 'Company News',
                'indexes': [models.Index(fields=['company'], name='tracker_com_company_698186_idx'), models.Index(fields=['last_fetched'], name='tracker_com_last_fe_b9c1ba_idx')],
            },
        ),
    ]
