# Generated by Django 4.2.25 on 2026-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0026_add_company_news_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defensecontract",
            options={
                "ordering": ["-article_date", "branch", "company_name_raw"],
                "verbose_name": "Government Contract",
                "verbose_name_plural": "Government Contracts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="defensecontract",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="defensecontract",
            name="award_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="USASpending Award ID (e.g., CONT_AWD_W912GY22C0021). Empty for war.gov records.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="defensecontract",
            name="awarding_agency",
            field=models.CharField(
                blank=True,
                help_text="Top-level agency (e.g., Department of Defense, Department of Homeland Security)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="defensecontract",
            name="awarding_sub_agency",
            field=models.CharField(
                blank=True,
                help_text="Sub-agency or bureau (e.g., Army Corps of Engineers)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="defensecontract",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("war_gov", "War.gov (DoD)"),
                    ("usaspending", "USASpending.gov"),
                ],
                db_index=True,
                default="war_gov",
                help_text="Source of this contract record",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="defensecontract",
            name="place_of_performance_state",
            field=models.CharField(
                blank=True,
                help_text="Two-letter state code for work location (NEW for USASpending)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="defensecontract",
            name="branch",
            field=models.CharField(
                choices=[
                    ("army", "Army"),
                    ("navy", "Navy"),
                    ("air_force", "Air Force"),
                    ("defense_logistics_agency", "Defense Logistics Agency"),
                    ("special_operations", "U.S. Special Operations Command"),
                    ("missile_defense", "Missile Defense Agency"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Military branch or agency awarding the contract (DoD classification)",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="defensecontract",
            name="source_url",
            field=models.URLField(
                help_text="URL of the source article or USASpending award page",
                max_length=512,
            ),
        ),
        migrations.AddIndex(
            model_name="defensecontract",
            index=models.Index(
                fields=["data_source", "article_date"],
                name="tracker_def_data_so_f49190_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="defensecontract",
            index=models.Index(
                fields=["awarding_agency"], name="tracker_def_awardin_ce67d2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="defensecontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("data_source", "war_gov")),
                fields=("source_url", "company_name_raw", "contract_number"),
                name="unique_wargov_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="defensecontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("data_source", "usaspending"),
                    models.Q(("award_id", ""), _negated=True),
                ),
                fields=("data_source", "award_id"),
                name="unique_usaspending_award",
            ),
        ),
    ]
