# Generated by Django 4.2.25 on 2026-02-12 16:30

from django.db import migrations


def backfill_war_gov_source(apps, schema_editor):
    """Backfill existing DefenseContract records with data_source='war_gov'."""
    DefenseContract = apps.get_model("tracker", "DefenseContract")
    
    # Update all existing records (which are from war.gov scraping)
    updated = DefenseContract.objects.filter(data_source="").update(data_source="war_gov")
    
    if updated > 0:
        print(f"Backfilled {updated} DefenseContract records with data_source='war_gov'")


def reverse_backfill(apps, schema_editor):
    """Reverse migration - clear data_source field."""
    DefenseContract = apps.get_model("tracker", "DefenseContract")
    DefenseContract.objects.filter(data_source="war_gov").update(data_source="")


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0027_add_usaspending_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_war_gov_source, reverse_backfill),
    ]
