# Generated by Django 4.2.25 on 2026-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0028_backfill_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="defensecontract",
            name="generated_internal_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="USASpending generated internal ID for award detail pages (e.g., CONT_AWD_W912GY22C0021_9700_...). Used to construct award URLs. Empty for war.gov records.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="defensecontract",
            name="award_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="USASpending Award ID (e.g., W912GY22C0021). Empty for war.gov records.",
                max_length=100,
            ),
        ),
    ]
