# Generated by Django 4.2.25 on 2026-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0029_add_generated_internal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="defensecontract",
            name="usaspending_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether this award's detail page is published on USASpending.gov. Always False for war.gov records.",
            ),
        ),
    ]
