# Generated by Django 4.2.25 on 2026-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0030_add_usaspending_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="talent_network",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user joined this company's talent network.",
            ),
        ),
    ]
