# Generated by Django 4.2.25 on 2026-02-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0031_company_talent_network"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyOperatingCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("normalized_city", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_cities",
                        to="tracker.company",
                    ),
                ),
            ],
            options={
                "ordering": ["city"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="tracker_com_company_8ca116_idx"
                    ),
                    models.Index(
                        fields=["normalized_city"],
                        name="tracker_com_normali_e612ae_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="companyoperatingcity",
            constraint=models.UniqueConstraint(
                fields=("company", "normalized_city"),
                name="uniq_company_normalized_city",
            ),
        ),
    ]
