# Generated by Django 4.2.25 on 2026-02-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0033_companynews_hidden_urls_user_articles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_date",
                    models.DateTimeField(help_text="Date and time of the interaction"),
                ),
                (
                    "is_phone",
                    models.BooleanField(default=False, help_text="Phone call"),
                ),
                (
                    "is_video",
                    models.BooleanField(default=False, help_text="Video call"),
                ),
                (
                    "is_text",
                    models.BooleanField(default=False, help_text="Text message"),
                ),
                ("is_chat", models.BooleanField(default=False, help_text="Chat / IM")),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person you interacted with (required)",
                        max_length=255,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the contact (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the contact (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the interaction", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="tracker.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-interaction_date"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="tracker_com_company_535186_idx"
                    ),
                    models.Index(
                        fields=["interaction_date"],
                        name="tracker_com_interac_48d2e6_idx",
                    ),
                ],
            },
        ),
    ]
