# Generated by Django 4.2.25 on 2026-03-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_add_company_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_5_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='highly_compensated_officer_5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='primary_place_of_performance_city_name',
            field=models.CharField(blank=True, help_text='Primary place of performance city (USASpending)', max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='primary_place_of_performance_country_name',
            field=models.CharField(blank=True, help_text='Primary place of performance country (USASpending)', max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='primary_place_of_performance_county_name',
            field=models.CharField(blank=True, help_text='Primary place of performance county (USASpending)', max_length=255),
        ),
    ]
