# Generated by Django 4.2.25 on 2026-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_defensecontract_highly_compensated_officer_1_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='duns_number',
            field=models.CharField(blank=True, help_text='Data Universal Numbering System (DUNS) number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='product_or_service_description',
            field=models.TextField(blank=True, help_text='Description of the product or service category'),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='recipient_doing_business_as_name',
            field=models.CharField(blank=True, help_text='Doing Business As (DBA) name', max_length=255),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='recipient_parent_duns',
            field=models.CharField(blank=True, help_text='Parent company DUNS number', max_length=20, null=True),
        ),
    ]
