# Generated by Django 4.2.25 on 2026-03-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_company_duns_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uei',
            field=models.CharField(blank=True, help_text='Unique Entity Identifier (UEI) from SAM.gov', max_length=12, null=True),
        ),
    ]
