# Generated by Django 4.2.25 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_company_uei'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamGovOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Contract title', max_length=500)),
                ('solicitation_number', models.CharField(blank=True, help_text='Solicitation number (e.g., N0001924R0012)', max_length=150, null=True, unique=True)),
                ('posted_date', models.DateField(help_text='Date the opportunity was posted')),
                ('type', models.CharField(help_text='Opportunity type (e.g., Presolicitation)', max_length=100)),
                ('base_type', models.CharField(blank=True, help_text='Base type', max_length=100, null=True)),
                ('award', models.JSONField(blank=True, help_text='Award details as JSON', null=True)),
                ('full_parent_path_name', models.CharField(blank=True, help_text='Agency hierarchy path', max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_office', models.CharField(blank=True, max_length=255, null=True)),
                ('naics_code', models.CharField(blank=True, max_length=20, null=True)),
                ('naics_codes', models.JSONField(blank=True, help_text='List of NAICS codes', null=True)),
                ('point_of_contact', models.JSONField(blank=True, help_text='Primary point of contact details', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_links', models.JSONField(blank=True, help_text='Links to attachments/resources', null=True)),
                ('ui_link', models.URLField(blank=True, help_text='Link to SAM.gov UI', max_length=500, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this opportunity was first fetched')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name_plural': 'SAM.gov Opportunities',
                'ordering': ['-posted_date', '-fetched_at'],
                'indexes': [models.Index(fields=['posted_date'], name='tracker_sam_posted__b04250_idx'), models.Index(fields=['solicitation_number'], name='tracker_sam_solicit_096552_idx')],
            },
        ),
    ]
