# Generated by Django 4.2.25 on 2026-03-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_samgovopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='samgovopportunity',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Full JSON response from API', null=True),
        ),
        migrations.AddField(
            model_name='samgovopportunity',
            name='response_date',
            field=models.DateField(blank=True, help_text='Deadline for response', null=True),
        ),
    ]
