# Generated by Django 4.2.25 on 2026-03-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0039_samgovopportunity_raw_response_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Feed title", max_length=500)),
                (
                    "feed_url",
                    models.URLField(
                        help_text="RSS Feed URL", max_length=1000, unique=True
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        blank=True,
                        help_text="Main website URL",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="Uncategorized",
                        help_text="Folder/Category name",
                        max_length=100,
                    ),
                ),
                (
                    "last_fetched",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful fetch",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="If False, will skip fetching"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RSS Feed",
                "verbose_name_plural": "RSS Feeds",
                "ordering": ["category", "title"],
            },
        ),
        migrations.AlterModelOptions(
            name="samgovopportunity",
            options={
                "ordering": ["-posted_date", "-fetched_at"],
                "verbose_name_plural": "Federal Contract Opportunities",
            },
        ),
        migrations.CreateModel(
            name="RSSArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Article headline", max_length=1000),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Direct link to article", max_length=2000, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Article summary or content snippet",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Author name", max_length=255, null=True
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True, help_text="Publication date from feed", null=True
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        help_text="Unique ID from feed", max_length=1000, unique=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_mentions",
                        to="tracker.company",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="tracker.rssfeed",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS Article",
                "verbose_name_plural": "RSS Articles",
                "ordering": ["-pub_date", "-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["pub_date"], name="tracker_rss_pub_dat_708ac8_idx"
                    ),
                    models.Index(fields=["guid"], name="tracker_rss_guid_d90a7c_idx"),
                ],
            },
        ),
    ]
