# Generated by Django 4.2.25 on 2026-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_rssfeed_alter_samgovopportunity_options_rssarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='samgovopportunity',
            name='product_service_code',
            field=models.CharField(blank=True, help_text='Product Service Code (PSC)', max_length=20, null=True),
        ),
    ]
