# Generated by Django 4.2.25 on 2026-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_samgovopportunity_product_service_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='samgovopportunity',
            index=models.Index(fields=['product_service_code'], name='tracker_sam_product_165938_idx'),
        ),
    ]
