# Generated by Django 4.2.25 on 2026-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_samgovopportunity_tracker_sam_product_165938_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensecontract',
            name='naics_code',
            field=models.CharField(blank=True, help_text='NAICS Code from USASpending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='defensecontract',
            name='product_service_code',
            field=models.CharField(blank=True, help_text='Product Service Code (PSC) from USASpending', max_length=20, null=True),
        ),
    ]
