# Generated by Django 4.2.25 on 2026-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0043_defensecontract_naics_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defensecontract",
            name="naics_description",
            field=models.CharField(
                blank=True,
                help_text="Description of the NAICS Code",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="defensecontract",
            name="product_service_code_description",
            field=models.CharField(
                blank=True,
                help_text="Description of the Product Service Code",
                max_length=255,
                null=True,
            ),
        ),
    ]
