# Generated by Django 4.2.25 on 2026-03-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0044_defensecontract_naics_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samgovopportunity",
            name="naics_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="samgovopportunity",
            name="product_service_code",
            field=models.CharField(
                blank=True,
                help_text="Product Service Code (PSC)",
                max_length=255,
                null=True,
            ),
        ),
    ]
