# Generated by Django 4.2.25 on 2026-03-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0045_alter_samgovopportunity_naics_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractIgnoreRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("term", "Term (Keyword)"),
                            ("naics", "NAICS Code"),
                            ("psc", "PSC Code"),
                        ],
                        default="term",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Exact code or substring to match", max_length=255
                    ),
                ),
                (
                    "should_delete",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, matching default contracts will be deleted permanently during import instead of just hidden.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["rule_type", "value"],
            },
        ),
    ]
