# Generated by Django 4.2.25 on 2026-03-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_alter_contractignorerule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractignorerule',
            name='naics_codes',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Select specific NAICS codes to ignore. If you leave this blank, the rule ignores EVERYTHING that matches the domain. If you select items here, the rule ONLY ignores items matching BOTH the Domain AND these NAICS codes.', to='tracker.naicscode'),
        ),
    ]
