# Generated by Django 4.2.25 on 2026-03-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_contractignorerule_naics_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractignorerule',
            name='rule_type',
            field=models.CharField(choices=[('term', 'Term (Keyword)'), ('naics', 'NAICS Code'), ('psc', 'PSC Code'), ('domain', 'Domain'), ('sector', 'NAICS Sector (2-digit)')], default='term', max_length=10),
        ),
    ]
